wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692855545.289177
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 1
      - 3
      - 5
