wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-07
architecture:
  desc: null
  value: ViT
dataset:
  desc: null
  value: customer
epochs:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692856040.841683
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 1
      - 3
      - 5
